### PR TITLE
Update config/widgets

### PR DESCRIPTION
**Pull request by keshto**

### CODE REVIEW

**Comment by keshto** [comment]
If you want I can open a PR per commit

**Comment by LBCrion** [comment]
Give me  bit of time to look at the alsa widget. We should be able to optimize it. (Also on my machine Mono: channel is empty, so may need to make it a bit more universal).

in t2.config - sakura terminal would be different from other configs. Perhaps I should switch terminal launchers to use $TERM in general

Everything else looks really good. Thank you for this!

**Comment by keshto** [comment]
Sure thing. If you want me to make the changes let me know or else you can suggest them to the PR or feel free to change after the fact.

**Comment by LBCrion** [comment]
For alsa, this is what I suggest for scanner section (this is using Left channel, but can be changed to Mono):
```
scanner {
  ExecClient("amixer sevents Master","alsa") {} # declare alsa trigger
  Exec("amixer sget Master") {
    AlsaVolume = RegEx("Left:.*[[]([0-9].*)%")
    AlsaMuted = RegEx("Left:.*[[].*[[]([A-Za-z].*)[]]")
  }
}
```

In addition, add ``trigger = "alsa"`` to the button widget. This way sfwbar will spawn the ``amixer sevents Master`` process and will listen for updates from it. Whenever an update is received, it will emit "alsa" trigger and refresh the widget's values. This way we only run ``amixer sget Master`` when the state of the sound output changes. This also avoids spawning grep, cut and td every time we update sound.

I admit to being a bit pedantic on these things, but the I wrote the first version of sfwbar precursor to speficially avoid constantly launching a bunch of processes to get system state.

**Comment by keshto** [comment]
Nice was not aware of `sevents`. Made the changes. Having `Left:` didn't work for me. Also, updated the regex to not gobble `.*` after the digits.

side note: more doumentation on regex parser being used and first/etc directives would be good :)

**Comment by LBCrion** [comment]
Sfwbar uses Glib regular expressions. The syntax is documented here:
https://developer-old.gnome.org/glib/stable/glib-regex-syntax.html
The aggregators (First, Last, Sum, Product) are described in the Scanner
section of the man page (towards the end of the section).

**Comment by LBCrion** [comment]
For terminal in t2.config, I suggest:
```
value = "utilities-terminal-symbolic"
css = "* { color: #ffffff }"
action = "sh -c $TERM"
```
This way, it should work out of the box with any terminal, so long as the user has $TERM defined. Although the icon doesn't look great for larger sizes (i.e. in twoline.config).

I haven't used tint2 myself, does it close the window on middle click by default?

**Comment by keshto** [comment]
What do you think of setting both the terminal and browser to `x-terminal-emulator` and  `x-www-browser` that way we can open the default browser and terminal of the system?

Middle click close is sorta standard on sway,  JWM, etc. I used tint2 exclusively way back when, and had the same middle click close but don't recall if that was me or default.

**Comment by LBCrion** [comment]
x-terminal-emulator and x-www-browser don't seem to be present in my default icon theme (Adwaita). That said, I'm not the biggest fan of symbolic terminal and browser icons either. I wonder if the best approach may be to pick a couple of free to distribute icons for these and package them with sfwbar, so we know the default configs work on all systems.

**Pull request merged**
