### PR TITLE
Enable  Drag-and-Drop enter action for all widgets

### PR DESCRIPTION
**Pull request by mozlima**
During a Drag-and-Drop operation, focus on the window associated with the taskbar item being hovered.

### CODE REVIEW

**Comment by mozlima** [comment]
@LBCrion

Hi, 
I would greatly appreciate your code review insights.

**Comment by mozlima** [comment]
> I'd suggest adding a small timeout (up to 500 ms) before applying the focus. Otherwise it may focus way more windows than desired by the user.

Maybe setting another window  function on wintree.c ?

```
guint wintree_focus_on_timer(guint timer_duration, gpointer uid) {
    static guint timeout_id = 0;
  
    if (timeout_id > 0) {
      g_source_remove(timeout_id);
      timeout_id = 0;
    }

    if (uid != 0) {
      timeout_id = g_timeout_add_once (timer_duration, (GSourceOnceFunc)wintree_focus, uid);
    }
    return timeout_id;
}

```


```
gboolean taskbar_item_on_drag_motion(GtkWidget *self, 
    GdkDragContext *context, gint x, gint y, guint time, gpointer user_data)
{
  window_t *win;
  GList *target;

  for (target = gdk_drag_context_list_targets(context); target; target = target->next) {
    gchar *name = gdk_atom_name(target->data);
    if(g_str_has_prefix(name, "flow-item-")) {
      g_free(name);
      return TRUE;
    }
    g_free(name);
  }

  win = taskbar_item_get_window(self);
  if(win != NULL)
    wintree_focus_on_timer(500, win->uid);
  return TRUE;
}
```

----


GTK has settings for double-click and keyboard repeat. Is there a setting for a timeout on drag?

**Comment by mozlima** [comment]
@LBCrion

This handles any drag type and the associated action
```
taskbar {
	.....
	action[8] = Focus
}
```

Is the action setting like `taskbar_item_action_exec(self, 8, NULL);` correct?

Additionally, how can we determine if the configuration requests the drop action to set up signals?

```
if (howtocheckifneed()){
  g_signal_connect(self, "drag-motion", G_CALLBACK(taskbar_item_on_drag_motion), NULL);
  g_signal_connect (self, "drag-leave", G_CALLBACK(taskbar_item_on_drag_leave), NULL);
}
```

Or should move the signal_connect code to `base_widget_set_action` ?

**Comment by LBCrion** [comment]
I think it would make sense to connect signals in base_widget_set_action `if(n==8)`, this would be consistent with how we handle enabling event tracking for other actions.

This is really nice and so much cleaner than my mock-up. What I wonder is whether we should move drag_motion and drag_leave functionality to base_widget alltogether? THis way it can be enabled for any base widget. For example if a user has a taskbar filter set to workspace, it would be nice to be able to activate the correct workspace by dragging a window first to pager (to activate a workspace) and then to a taskbar item to focus the window. And I've seen examples of people using buttons rather than a pager to activate individual workspaces as well, so I don't think we should limit this functionality just to FlowItems.

**Comment by LBCrion** [comment]
I added a commit to enable this for all base widgets, does this look ok to you?

**Comment by mozlima** [comment]
This is nice! Should I do something else?

**Comment by LBCrion** [comment]
I tidied up a few style nits and I think it's good to go. We should probably give the action a name, but I can add that later.

**Pull request merged**
