### PR TITLE
Initial implementation of cosmic-workspace-unstable-v1

### PR DESCRIPTION
**Pull request by Consolatis**
This is a partial implementation of the [cosmic-workspace-unstable-v1](https://github.com/pop-os/cosmic-protocols/blob/9c41b6b0ece1672c335e59bf670f8671ce66ed33/unstable/cosmic-workspace-unstable-v1.xml) protocol, 

I finally have decided to not wait another 3 years until the [official workspace protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) is accepted. This goes very much against my own believes that labwc should only use wlroots or wayland protocols but version 1 of the cosmic-workspaces protocol is basically the same as what is proposed in the upstream protocol. Using the cosmic variant also allows using the protocol without hiding it behind feature flags as the upstream protocol may change in incompatible ways before being accepted.

This PR allows to list the compositor workspaces including their state (being active or not) and to select the active workspace.
The protocol itself also allows to configure workspaces (create and remove) which is not implemented here (nor in labwc).

Some more caveats:
- workspace coordinates are not handled
- there is a `hidden` and `urgent` state per workspace that isn't handled in this PR
- workspace groups are completely ignored in this PR, only the workspaces themselves are shown
- the `output_enter` and `output_leave` group events are not handled in this PR

Most of the above are due to me not being versed enough in the sfwbar internals and thus not sure how to hook them up without complicating the other IPC systems.

This PR is based on top of #211, will rebase once that one is merged.
The codestyle in `cosmic-workspaces.c` is using tabs, I am completely fine adjusting that if it matters.

There is a labwc draft PR to test against:
- https://github.com/labwc/labwc/pull/2030

Alternatively testing against cosmic itself should hopefully also work but I didn't try that at all.

### CODE REVIEW

**Comment by LBCrion** [comment]
Nice! I'm travelling right now,  but will try to review these in detail on
Monday. At the first glance it looks good. I wonder if it's worth it to add
pointer to api specific data in workspace_t structure and put cosmic
specific flags in there to avoid iterating across two lists for every
callback.

**Comment by 01micko** [comment]
This seems to work great! When I get time I'll stuff around with the widget to get it looking nice :) Thanks @Consolatis for pursuing this!

**Comment by 01micko** [comment]
Screeny https://github.com/labwc/labwc/pull/2030#issuecomment-2255626350

**Comment by LBCrion** [comment]
Apologies for starting with pedantic stuff - ident formatting. I am looking at the substance as well :)

**Comment by 01micko** [comment]
Tweaked config


https://github.com/user-attachments/assets/3113c000-5861-4456-a1a2-d606e3bfb2eb

**Comment by LBCrion** [comment]
> I think this isn't working @LBCrion after your latest commit to @Consolatis PR

Do you mean the title_width property isn't working  for the taskbar? The PR should have no impact on this. Does it work with beta15?

> except they are sorted alphabetically.

You should be able to add `sort = false` property to the pager widget.

**Comment by LBCrion** [comment]
@Consolatis, are there any plans to implement `create_workspace` in labwc? The ability to create workspaces from the pager (in the form of pinned workspaces) is quite useful.

Also, is there a way to rename a workspace on the fly? I would like to test the handling of workspace/pin name collision scenario.

**Comment by Consolatis** [comment]
> @Consolatis, are there any plans to implement `create_workspace` in labwc? The ability to create workspaces from the pager (in the form of pinned workspaces) is quite useful.

No immediate planes at least. This is something that might be implemented in labwc at some point as the ability to create / rename / delete workspaces is already available within labwc itself (and cosmic workspaces should already mirror these changes).
 
> Also, is there a way to rename a workspace on the fly? I would like to test the handling of workspace/pin name collision scenario.

Version 2 of the protocol added a rename action and corresponding capability.
For testing you can modify the workspace names (and/or count) in rc.xml and then call the `Reconfigure` action.

**Comment by Consolatis** [comment]
I've added a [commit](https://github.com/labwc/labwc/pull/2030/commits/94b744dd59e403a43b7bb7b489408b60a13b75f7) to the labwc draft PR which allows for creating workspaces. Note that it will be reverted before merging and is not a complete implementation (e.g. once you `Reconfigure` labwc the new workspaces will be removed or potentially renamed when the ws count in rc.xml was increased).

**Comment by LBCrion** [comment]
Thank you, I got the creation working correctly now. Is the idea for the stable implementation for now to only support workspace definition changes via Reconfigure, Since any changes from other sources would need to be reconciled vs the config?

It would probably be cleanest to disable to pins until dynamic workspace creation is supported. I think on sfwbar side, I may introduce a corresponding capability and only display pins if it's enabled.

**Comment by Consolatis** [comment]
> Is the idea for the stable implementation for now to only support workspace definition changes via Reconfigure, Since any changes from other sources would need to be reconciled vs the config?

Yes, that is the main stopper for labwc in regards to workspace creation.
We could allow workspace creation and removal (via the REMOVE cap / remove() request) and make them survive a `Reconfigure` action (by additionally storing them in some external list) but as Labwc never writes to the config the workspaces would be gone on the next labwc restart. That feels somewhat inconsistent so for now Labwc will only support activation.

**Comment by LBCrion** [comment]
I think I finally got this PR into state that's ready for merging. @Consolatis, I would appreciate if you could review it to see if I missed / screwed up anything.
I'll be away from the computer for the next week and will probably look to merge it the week unless any issues pop up with it.

@01micko, if you get a chance to test the latest version of this PR, it would be much appreciated.

**Comment by Consolatis** [comment]
> I think I finally got this PR into state that's ready for merging. @Consolatis, I would appreciate if you could review it

Will do during the week, thanks for your constant work on sfwbar, really appreciate your dedication.

**Comment by 01micko** [comment]
Thanks guys for the great efforts put into this!

On initial look it works great - both labwc (20 mins ago so latest wip/cosmic_wokspaces) and sfwbar on latest commits.

The 'pins' issue is solved.

Couple of warnings on start up with bone stock config:

```
~$ sfwbar
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:23886): GLib-CRITICAL **: 07:41:53.635: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
```

I also have a vertical config I've been testing and that works best with this in `rc.xml`, this is because `workspaces` doesn't fit in a 12x12  container and gets elipsised.

```xml
  <desktops>
    <popupTime>1000</popupTime>
    <names>
      <name>1</name>
      <name>2</name>
      <name>3</name>
      <name>4</name>
    </names>
  </desktops>
```

The only warnings I get with that is widget conflicts - so _my_ problem.

Which brings me to the UX

 1. I haven't tested with translations yet (will soon) but is it expected that 'workspaces' will be translated when shown in sfwbar? (probably not)
 2.  If you had say 6 workspaces configured that would take up a lot of bar real estate. I usually have at least 2 and often 4.  Could we do some string manipulation to just show the desktop number? Or at least make it optional.
 3. CSS - probably more documentation than anything else. I _almost_ have my vertical config as I want.
 

Many thanks @Consolatis and @LBCrion :smile:

**Comment by 01micko** [comment]
Vertical demo


https://github.com/user-attachments/assets/287387f2-b694-4a0e-ae04-67283c64249c

**Comment by Consolatis** [comment]
Using either unicode symbols or emoticons might also work, e.g. something like
```xml
  <desktops>
    <names>
      <name>📺</name>
      <name>💻</name>
      <name>📜</name>
    </names>
  </desktops>
```

**Comment by 01micko** [comment]
> > I think this isn't working @LBCrion after your latest commit to @Consolatis PR
> 
> Do you mean the title_width property isn't working for the taskbar? The PR should have no impact on this. Does it work with beta15?

I didn't realise it wan't part of the stock config! Sorry about that noise. All works as expected with `title_width = 25`

**Comment by 01micko** [comment]
I suppose this makes sense :stuck_out_tongue_closed_eyes: 

canasta

Still wrestling with the CSS!

**Comment by 01micko** [comment]
Translations do survive. Tested with es_ES locale.

**Comment by 01micko** [comment]
Even works with RTL

ar_locale

**Comment by LBCrion** [comment]
> Couple of warnings on start up with bone stock config:
> 
> ```
> ~$ sfwbar
> i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
> (sfwbar:23886): GLib-CRITICAL **: 07:41:53.635: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
> ```

These should hopefully be fixed in the main branch now.

**Comment by Consolatis** [comment]
Sorry, took a bit longer to come back to this PR. From the protocol perspective all changes look fine to me.

Regarding the path forward, labwc will have a release around Aug. 16th (without cosmic-workspace support) and will then likely merge the server side implementation in its master branch shortly after that. Obviously completely up to you if you want to sync it up with labwc or merge this PR before / after.

There might be some more minor changes on the labwc side of the PR but nothing that should change anything regarding the protocol.

**Comment by LBCrion** [comment]
No problem at all. I made a few more small changes in the meantime - namely added an invalid state to avoid updating pager items more often than needed (updating gtk widgets is relatively cpu intensive). 
I probably would prefer to merge this before labwc, or at least the part of this PR that deal with changes to workspace API. But I would be curious to see how the ext-workspaces PR progresses in case there is hope of it getting merged soon.

**Comment by LBCrion** [comment]
One more thing I had on my mind that would be relevant to this PR is handling of wayland globals. Currently sfwbar registers multiple global handlers in order to enforce the priority of protocols. I think it would be cleaner to get a list of interfaces available and then bind to them if and when necessary (I think we'll need to do this if we implement cosmic workspaces and then need to decide if we want to bind to this interface or to ext-workspaces once that's avaible).

My thinking so far is to do the following:
1) register a global handler
2) do a roundtrip to get interfaces
3) have the global save the information on all interfaces that come through
4) switch semaphore that will tell the global handler to stop processing new interfaces.
5) call all of the sfwbar _init functions in order and let each out rummage through the interface list the global handler saved to determine if it wants to bind to an interface.

The question is, can we be confident that all the interfaces will be advertised on the first roundtrip and is there a chance of them going away in the future before we can bind to them?

**Comment by Consolatis** [comment]
> The question is, can we be confident that all the interfaces will be advertised on the first roundtrip and is there a chance of them going away in the future before we can bind to them?

Yes, I think so. It is already the case with outputs but technically compositors can remove (`global_remove` event on the `wl_registry`) and add globals at any point in time. I've never seen compositors do this outside of the `wl_output` case though.

**Comment by LBCrion** [comment]
I added the interface storage list and updated all protocol implementation to use it in this PR. It seems to work well and should allow to mediate between ext-workspaces and cosmic-workspaces in the future.

**Comment by Consolatis** [comment]
Thanks for merging and all your improvements over the initial PR!
Will follow with the server side implementation in labwc in a few days.

**Comment by 01micko** [comment]
@Consolatis @LBCrion Cosmic workspaces just got merged in `labwc` so will be in `0.8.1` :tada:

**Pull request merged**
